### ISSUE TITLE
使用fetch请求传输json数据报错

### ISSUE THREAD

**Issue by WN0904** [react-native-oh-library/react-native-blob-util#34]
### 描述 / Description

使用fetch请求传输json数据报错`getABData fail，check file is exists`

### 复现步骤 / Steps to reproduce

复现代码
````js
 const response = await RNFetchBlob.config({
      // Add this line to ensure the response will be treated as binary data
      fileCache: false,
    }).fetch(
      'POST',
      global.URL_XUNJI + uri,
      {
        'Content-Type': 'application/json',
        'Accept-Encoding': 'gzip',
        Authorization: `Bearer ${global.token}`,
      },
      JSON.stringify(body),
    );
````

### 库版本 / Library version

0.19.6-0.0.11

### React Native OpenHarmony version

0.72.29

### 构建类型 / Build type

None

### 设备 / Device

None

### 已悉知 / Acknowledgements

Yes

**Comment by hejun041** [comment]
上传失败 getABData 失败，检查文件是否存在
'Content-Type' : 'multipart/form-data'
版本：0.19.6-0.0.16
